---
title: "Assignment3"
author: "Jenny Balmagia and Jessica Jagdeo"
date: "March 9, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```


```{r}
#Generate sample data for WatershedStorage()

nsample = 100

# sample precipitation data, inches/year
precip_waterstorage = rnorm(mean = 7, sd = 2, n = nsample)
# sample evaporation data, inches/year
evap_waterstorage = rnorm(mean = 0.5, sd = 0.15, n = nsample)
# sample runoff data, inches/year
runoff_waterstorage = rnorm(mean = 0.7, sd = 0.2, n = nsample)

```


```{r}
#Generate sample data for snow_v_rain()

days = 365
#Table with column for precipitation (inches) and column for temperature (F) from same observation

climate = data.frame(precip = rnorm(mean = 0.1, sd = 0.08, n = days), temp = rnorm(mean = 50, sd = 25, n = days))

```

```{r}
# Generate sample data for MaxPrecip()

# rainfall in inches/day
rainfall = rnorm(mean = 7, sd = 2, n = 1460)
# daily dates for 1995
date = rep(seq(from = as.Date("1995-01-01"), to = as.Date("1995-12-31"), by = 'day'), 4)
# rainfall station data for Cachuma, Gibraltar, Jameson, San Marcos
station = rep(c("Cachuma", "Gibraltar", "Jameson", "San Marcos"), times = 1, each = 365)

# combine the values above into a data frame
precip <- data.frame(date, station, rainfall)

```

